FROM build-llava as build-llava-training
COPY environment-training.yaml /opt/build/llava
SHELL ["/bin/bash", "-eEx", "-o", "pipefail", "-c"]
RUN <<-EOF

    export CI=1
    micromamba install -v -y -n "${ENV_NAME}" -f /opt/build/llava/environment-training.yaml
    micromamba run -n "${ENV_NAME}" python -m pip cache purge
    micromamba clean -y --all

EOF
