name: llava

channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - python~=3.12
  - pytorch::pytorch-cuda~=12.1
  - pytorch::pytorch=*=*cuda12.1* 
  - pytorch::torchvision
  - numpy
  - scikit-learn>=1.2.2
  - accelerate>=0.21.0
  - bitsandbytes
  - einops>=0.6.1
  - fastapi
  - gradio>=4.16.0
  - gradio-client>=0.8.1
  - httpx>=0.24.0
  - markdown2
  - peft
  - pip
  - pydantic
  - requests
  - sentencepiece>=0.1.99
  - shortuuid
  - timm>=0.6.13
  - tokenizers>=0.15.1
  - transformers=4.37.2
  - uvicorn
  - protobuf
  - pip:
      - einops-exts>=0.0.4
